
<div class="card border-<?= ($group->status) ? 'success' : 'warning'; ?>">
    <div class="card-header text-center bg-<?= ($group->status) ? 'success text-white' : 'warning text-dark'; ?>">
        <img id="<?=$group->externalNumber;?>_img" src="img/closed.png"
             height="32" width="32"
             onclick="bodyDisplay('<?=$group->externalNumber;?>');"><?= $group->externalNumber; ?>
    </div>
    <div class="card-body" style="display: none" id="<?=$group->externalNumber;?>">
        <table class="table table-bordered table-hover small border-dark"
               style="line-height: 0.9rem">
            <tr>
                <th>Время звонка</th>
                <th>А номер</th>
                <th>Внешний номер</th>
                <th>Б номер</th>
                <th>Длительность</th>
                <th>Запись</th>
            </tr>
        <?php foreach ($group->calls as $call):?>
            <?php
                $path = "";
                if ($call->recordingfile){
                    $time = strtotime($call->calldate);
                    $path = date("Y/m/d/", $time);
                }
            ?>
        <tr class="alert alert-<?= ($call->status) ? 'success': 'warning'; ?>">
            <td><?= $call->calldate; ?></td>
            <td><?= $call->srcNumber; ?></td>
            <td><?= $call->did; ?></td>
            <?php if ($call->status):?>
                <td><?= $call->dstNumber; ?></td>
                <td><?= gmdate("i:s", $call->duration); ?></td>
                <td>
                    <?php if ($call->recordingfile): ?>
                    <a target="_blank" href="records/<?= $path . $call->recordingfile;?>">
                    <img src="img/play.png"
                         height="16" width="16">
                    </a>
                    <?php endif; ?>
                </td>
            <?php else: ?>
                <td><?= implode(', ', array_unique($call->dstlist)); ?></td>
                <td><?= gmdate("i:s", 0); ?></td>
                <td></td>
            <?php endif; ?>
        </tr>
        <?php endforeach; ?>
        </table>
    </div>
</div>